---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-api
  labels:
    app: devsecops-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops-api
  template:
    metadata:
      labels:
        app: devsecops-api
    spec:
      containers:
        - name: api
          image: devsecops-api:v1
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "production"
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
---
apiVersion: v1
kind: Service
metadata:
  name: devsecops-api-service
spec:
  selector:
    app: devsecops-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
